Repository simonihmig/ember-window-mock, pull requests merged in 2024-07, with the labels that each got.

#567 Fix broken npm package
  ember-window-mock/package.json
Labels: bug

#569 Fix release-it setup
  CHANGELOG.md
  ember-window-mock/package.json
  package.json
  test-app/package.json
  yarn.lock
Labels: internal

#571 Fix missing types in published package
  ember-window-mock/package.json
Labels: bug

#572 Support mocking window.location.origin
  ember-window-mock/src/test-support/-private/mock/location.js
  test-app/tests/unit/window-mock-test.ts
Labels: bug

#575 Add createMockedWindow helper for mocking window.parent or other explicit window instances
  README.md
  ember-window-mock/index.d.ts
  ember-window-mock/src/test-support/-private/setup-window-mock.js
  ember-window-mock/src/test-support/-private/window.js
  ember-window-mock/src/test-support/index.js
  test-app/tests/unit/create-mocked-window-test.ts
  test-app/tests/unit/run-window-tests.ts
  test-app/tests/unit/window-mock-test.ts
Labels: enhancement

#577 Fix default export positions
  ember-window-mock/package.json
Labels: bug
